global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "/etc/prometheus/*.rules.yml"

scrape_configs:
  - job_name: 'prom'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'alert'
    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: 'traefik'
    static_configs:
    - targets: ['traefik:8080']